# Generated by Django 3.0.3 on 2022-03-28 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_has_perm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='has_perm',
        ),
    ]
